### ISSUE TITLE
Run/Reload on save

### ISSUE THREAD

**Issue by rx2347** [TobiahZ/processing-vscode#103]
I don't know if this is possible at all, but we all got used to run on save features on linters or prettier for example, so maybe that's an option? Probably need to check for running tasks first and quit them though...?

**Comment by AvinZarlez** [comment]
To clarify, what you want is when your save your file for it to automatically execute the task to start processing?

**Comment by rx2347** [comment]
> To clarify, what you want is when your save your file for it to automatically execute the task to start processing?

Exactly!

**Comment by AvinZarlez** [comment]
While I would consider an optional off by default setting if someone wanted to make it and submit a PR... This is probably out of scope for this extension.

There are other extensions that when combined could create the same effect.  Since this extension creates a standard VSCode task. Such as https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.triggertaskonsave (NOTE: I have never used, downloaded or tested that extension. I cannot speak for it)
