### ISSUE TITLE
Keep running into create Processing projects.pde first

### ISSUE THREAD

**Issue by ayush-seth** [TobiahZ/processing-vscode#5]
How do I get rid of this? It worked with another project of mine but whenever I try to build task file for this project, this comes up

![image](https://cloud.githubusercontent.com/assets/24858182/26009492/af748c28-3766-11e7-8c8a-860bca1c1b78.png)

**Comment by AvinZarlez** [comment]
This is an error message from Processing, not from the extension itself.

You seem to have opened your project from a "projects" folder, and then have you actual project in a subfolder from there. The extension runs the project from the base folder you have open (How else would it know which sub project you're supposed to run?)

Since you are running it from a base folder (that I'll bet is named "processing") it's looking for the FolderName.pde file.

Try reopening VSCode under the PerlinTree folder and try again.

**Comment by ayush-seth** [comment]
Thanks, directly opening the PerlinTree folder fixed it, the task file was created successfully but now, doing `ctrl+shift+b` does nothing, no processing window is opened, and the output tab doesn't show anything either. `out/source/PerlinTree.java` did get created.

**Comment by AvinZarlez** [comment]
Did you remember to add Processing to your path as described in the readme? https://github.com/TobiahZ/processing-vscode#add-processing-to-path

**Comment by ayush-seth** [comment]
Oh nevermind, my bad, the output tab was not set to show tasks output, turns out I had a missing constructor, thanks, everything works fine now!

**Comment by AvinZarlez** [comment]
Glad you got it working! Let me know if you'd like to see any features from this extension (or would like to contribute a feature yourself!)

**Comment by ayush-seth** [comment]
Something I didn't find was auto-complete/snippets for PVectors and I wish that was there since I use that in almost all my sketches.
