### ISSUE TITLE
Backslashes are getting ommited on Windows [BUG] 

### ISSUE THREAD

**Issue by sophuric** [TobiahZ/processing-vscode#68]
**Describe the bug**
Hi. When I try to build, the path doesn't have any backslashes.

The output says:

```
C:UsersMyUserDesktopProject does not exist.
```

**To Reproduce**
1. Use [`ProcessingTasks.json`](https://github.com/TobiahZ/processing-vscode/blob/master/ProcessingTasks.json) as `.vscode\tasks.json`
2. Build
3. Output says file path but without the backslashes

**Expected behavior**
Backslashes will be there,
with something like: `C:\Users\MyUser\Desktop\Project\`

**VSCode (from Help &rarr; About):**
- Version: 1.36.1 (system setup)
- Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
- Date: 2019-07-08T22:58:59.274Z
- Electron: 4.2.5
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT ia32 6.3.9600

**Comment by AvinZarlez** [comment]
Are you setting processing.path ?

From the readme:

> What if you cannot, or do not want to add Processing to your path?
> 
> Simply modify the processing.path setting to follow the path to wherever processing is installed on your machine. Be sure to remember to keep the processing-java at the end of the path!
> 
> To change settings in VSCode, here is a link to the official documentation.
> 
> **(Remember, for Windows be sure to turn any `"\"` into `"\\"`!)**

Single slashes on windows are part of codes, like how `"\n"` is a new line. `"\\"` is translated to `\` and single slashes are just removed.

**Comment by sophuric** [comment]
@TobiahZ I have set the path, since I can always press <kbd>![windows]</kbd>+<kbd>![R]</kbd> to open the run dialog, type `processing`, and it opens.

[windows]: https://user-images.githubusercontent.com/48314599/61515625-6aef2180-aa46-11e9-8204-3f0dd57d1c10.png
[R]: https://user-images.githubusercontent.com/48314599/61515812-d46f3000-aa46-11e9-8598-5b44ab59907d.png

**Comment by AvinZarlez** [comment]
If processing is set up in your path (as you said, you can Windows+R and type just processing and it runs) you should NOT set a value to the processing.path VSCode setting.

So when you say "I have set the path" - do you have any value assigned to the processing.path setting? If so, what?

**Comment by sophuric** [comment]
@TobiahZ Oh, I thought you meant the env `%path%` variable, but it still works.
Anyways, I just realised what you said

> Single slashes on Windows are part of codes, like how "\n" is a new line. "\\" is translated to \ and single slashes are just removed.

That explains everything!

**Comment by lucasoeth** [comment]
> @TobiahZ Oh, I thought you meant the env `%path%` variable, but it still works.
> Anyways, I just realised what you said
> 
> > Single slashes on Windows are part of codes, like how "\n" is a new line. "\" is translated to \ and single slashes are just removed.
> 
> That explains everything!

could I ask how you fixed the problem?

**Comment by AvinZarlez** [comment]
@lucasoeth  I can't speak for @wooden-utensil , but I assume the issue was having single slashes in a file URI.

Example: `C:\Users\MyUser\Desktop\Project`

However, on Windows, the single backslash character `\` is special. It's used to insert special symbols.

Example: `This is on line one\nThis is line two` would be rendered as:

```
This is on line one
This is line two
```

Since a `\n` is replaced with a new line character.

Single slashes are simply automatically removed if they aren't followed by one of the key letters it's looking for.

Hence why `C:\Users\MyUser\Desktop\Project` might turn into `C:UsersMyUserDesktopProject`

Thus, you want to use the special character `\\` to create a single backslash.

If you are using the processing.path setting variable on windows, make sure your folder location URI uses double slashes!

**Comment by sophuric** [comment]
Hang on, I think I was using Bash, but I was somehow using backslashes, so the backslashes get removed.
