### ISSUE TITLE
[Question]  Ctrl+Click to open code in other file

### ISSUE THREAD

**Issue by floatPond** [TobiahZ/processing-vscode#82]
Hi there!

I am not too sure if this is related to the extension itself, or more a Visual Studio Code thing.

In the Processing IDE, it was possible to Ctrl+Click a piece of code and if that was in another file, it would open that file in its tab. Is that possible in Visual Studio Code when doing Processing?

Thanks!

Edit: I think this may also be referred to as 'Go to definition'?

**Comment by AvinZarlez** [comment]
It should be a built-in VSCode thing, since the processing support is based on the built-in Java support.

But I imagine it doesn't seem to be working for you? https://code.visualstudio.com/Docs/editor/editingevolved#_go-to-definition

Labeling this invalid and closing since it's not an extension issue, I don't think. But can reopen it if when trying to figure out why it doesn't work for you if there is a processing extension-specific fix or instructions that could be useful for others.

**Comment by floatPond** [comment]
> It should be a built-in VSCode thing, since the processing support is based on the built-in Java support.
> 
> But I imagine it doesn't seem to be working for you? https://code.visualstudio.com/Docs/editor/editingevolved#_go-to-definition
> 
> Labeling this invalid and closing since it's not an extension issue, I don't think. But can reopen it if when trying to figure out why it doesn't work for you if there is a processing extension-specific fix or instructions that could be useful for others.

That is the exact link I have been using to try and get it to work to no avail. It seems to work with my other projects in Python and HTML, but not in Processing
