### ISSUE TITLE
Add extension to Open VSX registry

### ISSUE THREAD

**Issue by 12people** [TobiahZ/processing-vscode#91]
**Is your feature request related to a problem? Please describe.**
I use VSCodium (an open-source, privacy-minded VS Code fork) instead of VS Code. That uses the Open VSX Registry as its source for extensions rather than Visual Studio Marketplace. Since this extension is not on the Open VSX Registry, it can't be easily installed in VSCodium.

**Describe the solution you'd like**
I would very much appreciate it if this extension was on [Open VSX](https://open-vsx.org/about) as well.

**Comment by 12people** [comment]
Here is a [guide on publishing to the Open VSX Marketplace](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by maxfarrell** [comment]
I believe I'm having the same problem - can't find this in the marketplace. Any updates on installing on vscodium?

**Comment by le-jun** [comment]
Known issue, workaround here https://github.com/TobiahZ/processing-vscode/issues/88#issuecomment-676250992

**Comment by AvinZarlez** [comment]
Yes, I have not submitted to the Open VSX registry. Ideally I'd love to have time to rework this extension a bit, and perhaps automate uploading to both open VSX and the VS Code marketplace. But I have extremely limited time lately due to work/life for any extension development, and this would be lower priority.
