### ISSUE TITLE
"Error: The import processing cannot be resolved"

### ISSUE THREAD

**Issue by alexErh** [TobiahZ/processing-vscode#96]
Hello, 
I am trying to use Processing in VScode, but I can't run my sketch, because the processing packages can not be imported. I don't understand, why it happens.
I followed this [steps](https://marketplace.visualstudio.com/items?itemName=Tobiah.language-pde&ssr=false#add-processing-to-path). Mabe have to do something else?

I'm using Linux Mint.

**Comment by AvinZarlez** [comment]
What exactly is the error? Can you post the full error message/logs, and maybe some of your code? That would be helpful in understanding what doesn't work.

Can you run a very basic "Hello world" processing program? If so, then the problem isn't with VSCode, as that is just linking to your processing install.

**Comment by alexErh** [comment]
![Screenshot Error](https://user-images.githubusercontent.com/80600675/111324585-32647880-866b-11eb-88f7-5823a3141116.png)

This is, what i get.

**Comment by AvinZarlez** [comment]
That is because .java files are handled by default by VSCode as... well, Java. And in straight java there isn't a processing class to include. For the code you are working on you use pde https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file

Either way your code should actually run when you execute it with processing, this extension doesn't provide intellisense like that.

Besides, isn't that your output? Shouldn't that folder be ignored in your editor?
